config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :users
  resources :board

  get '/users', to: "users#index"
  root "game#index"

  get "/queue_page", to: 'game#queue_page'
  get "/game_page", to: 'game#game_page', as: 'game_path'

  post "/queue", to: 'session#create'
  # post "/game_page", to: 'board#create'

  post "/move", to: "board#move"

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post 'create'    => 'game#create'
  resources :game
  mount ActionCable.server => "/cable"
end

app/models/user.rb
class User < ApplicationRecord
    has_many :messagee, foreign_key: :receiver_id, class_name: 'Message'  
    has_many :senders, through: :messagee
    has_many :messaged, foreign_key: :sender_id, class_name: 'Message'
    has_many :receivers, through: :messaged
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index 
        @users = User.all 
    end 

    def show 
        @sender = User.find(params[:users][:ids])
        @receiver = User.find(params[:receiver_id])
        @messages = Message.where(sender_id: @sender.id, receiver_id: @receiver.id).or(Message.where(sender_id: @receiver.id, receiver_id: @sender.id))
        @chat_id = [@sender.id, @receiver.id].sort.join("") #generates a unique identifier for a pair of user 
    end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.erb
<div>
    <h1>Contacts</h1>
    <div>
        <%= form_for :users, :url => "/users/show",  :html => { :method => 'GET' } do |f| %>
            I am: <%= f.collection_select :ids, @users, :id, :name %> <br>
            <%= f.label "Who do you want to chat with?" %> <br>
            
            <% @users.each do |user| %>
                <%= radio_button_tag(:receiver_id, user.id) %>
                <%= label_tag(:name, user.name) %> <br>
            <% end %>
            <%= f.submit "Chat"%>
        <% end %>
    </div>
</div>

app/views/users/show.erb
<div>
    <h2><%=@sender.name %> contacting <%=@receiver.name%></h2>
    <div id="messages">
        <% @messages.each do |message| %>
            <p><%= message.sender.name %>: <%= message.text %></p>
        <% end %>
    </div>
    
    <%= form_tag messages_path  do %>
        <div>
            <%= text_field_tag :message, nil ,  placeholder: 'Type message here...', class: 'form-control' %>
            <%= hidden_field_tag "receiver_id", @receiver.id %>
            <%= hidden_field_tag "sender_id", @sender.id %>
            <%= hidden_field_tag "chat_id", @chat_id %>
            <%= submit_tag "Send", data: { disable_with: false } %>
        </div>
    <% end %>
</div>